title: o11yfest
email: organizers@o11yfest.org
description: >- # this means to ignore newlines until "baseurl:"
  A virtual event to celebrate observability in our systems and software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://o11yfest.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: o11yfest
github_username:  o11yfest
show_github: false
google_analytics_tag: G-SQ4YJP5LND
produrl: "https://o11yfest.org"

direct_registration_link: "https://ti.to/o11yfest/2021"
registration_link: "/attend"

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

include:
  - _pages

header_pages:
  - title: "-about"
    url: /about
  - title: "-attend"
    url: /attend
  - title: "-cfp"
    url: /cfp
  - title: "-agenda"
    url: /agenda
  - title: "-code-of-conduct"
    url: /code-of-conduct
  - title: "-sponsor"
    url: "/sponsor"
  - title: "-contact"
    url: "/contact"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
